#include "CanvasExporter.h"

#include <cmath>
#include <fstream>
#include <sstream>

namespace canvas
{
    namespace
    {
        std::string ColorToRaylibCode(const ColorRGBA &c)
        {
            std::ostringstream oss;
            oss << "Color{" << static_cast<int>(c.r) << ", " << static_cast<int>(c.g) << ", "
                << static_cast<int>(c.b) << ", " << static_cast<int>(c.a) << "}";
            return oss.str();
        }

        void DrawPixelCircle(const Vector2 &center, float radius, const Color &color)
        {
            const float cellSize = 1.0f;
            const int minCellX = std::max(0, static_cast<int>(std::floor((center.x - radius) / cellSize)));
            const int maxCellX = static_cast<int>(std::floor((center.x + radius) / cellSize));
            const int minCellY = std::max(0, static_cast<int>(std::floor((center.y - radius) / cellSize)));
            const int maxCellY = static_cast<int>(std::floor((center.y + radius) / cellSize));
            const float radiusSq = radius * radius;

            for (int y = minCellY; y <= maxCellY; ++y)
            {
                for (int x = minCellX; x <= maxCellX; ++x)
                {
                    const float px = static_cast<float>(x) + 0.5f;
                    const float py = static_cast<float>(y) + 0.5f;
                    const float dx = px - center.x;
                    const float dy = py - center.y;
                    if (dx * dx + dy * dy <= radiusSq)
                    {
                        DrawPixel(x, y, color);
                    }
                }
            }
        }
    }

    std::string CanvasExporter::ExportCpp(const CanvasDocument &doc, const std::string &functionName)
    {
        std::ostringstream out;
        out << "#include \"raylib.h\"\n\n";
        out << "void " << functionName << "()\n";
        out << "{\n";
        out << "    // Generated by the canvas tool.\n\n";

        for (const auto &px : doc.pixels)
        {
            out << "    DrawRectangle(" << px.x << ", " << px.y << ", 1, 1, " << ColorToRaylibCode(px.color) << ");\n";
        }

        out << "}\n";
        return out.str();
    }

    bool CanvasExporter::SaveCpp(const std::filesystem::path &path, const CanvasDocument &doc, const std::string &functionName)
    {
        std::ofstream file(path, std::ios::binary);
        if (!file.is_open())
        {
            return false;
        }
        file << ExportCpp(doc, functionName);
        return true;
    }

    bool CanvasExporter::LoadPng(const std::filesystem::path &path, CanvasDocument &doc)
    {
        Image image = LoadImage(path.string().c_str());
        if (image.data == nullptr)
        {
            return false;
        }

        const int targetFormat = PIXELFORMAT_UNCOMPRESSED_R8G8B8A8;
        ImageFormat(&image, targetFormat);

        doc.Clear();
        doc.settings.width = image.width;
        doc.settings.height = image.height;
        doc.settings.cellSize = 1;

        Color *pixels = LoadImageColors(image);
        if (pixels == nullptr)
        {
            UnloadImage(image);
            return false;
        }

        for (int y = 0; y < image.height; ++y)
        {
            for (int x = 0; x < image.width; ++x)
            {
                const Color color = pixels[y * image.width + x];
                doc.pixels.push_back(PixelPaint{x, y, ToRGBA(color)});
            }
        }

        UnloadImageColors(pixels);
        UnloadImage(image);
        return true;
    }

    bool CanvasExporter::SavePng(const std::filesystem::path &path, const CanvasDocument &doc)
    {
        Image image = GenImageColor(doc.settings.width, doc.settings.height, BLANK);
        if (image.data == nullptr)
        {
            return false;
        }

        for (const auto &pixel : doc.pixels)
        {
            if (pixel.x < 0 || pixel.y < 0 || pixel.x >= doc.settings.width || pixel.y >= doc.settings.height)
            {
                continue;
            }
            ImageDrawPixel(&image, pixel.x, pixel.y, ToColor(pixel.color));
        }

        const bool ok = ExportImage(image, path.string().c_str());
        UnloadImage(image);
        return ok;
    }
}
