#include "../raylib/include/raylib.h"

#include <algorithm>
#include <cmath>
#include <cstdint>
#include <filesystem>
#include <fstream>
#include <sstream>
#include <string>
#include <utility>
#include <vector>

namespace fs = std::filesystem;

namespace
{
    struct ColorRGBA
    {
        unsigned char r{};
        unsigned char g{};
        unsigned char b{};
        unsigned char a{255};
    };

    static Color ToColor(const ColorRGBA &c)
    {
        return Color{c.r, c.g, c.b, c.a};
    }

    static ColorRGBA ToRGBA(const Color &c)
    {
        return ColorRGBA{c.r, c.g, c.b, c.a};
    }

    static std::string ColorToRaylibCode(const ColorRGBA &c)
    {
        std::ostringstream oss;
        oss << "Color{" << static_cast<int>(c.r) << ", " << static_cast<int>(c.g) << ", "
            << static_cast<int>(c.b) << ", " << static_cast<int>(c.a) << "}";
        return oss.str();
    }

    static float Distance(Vector2 a, Vector2 b)
    {
        const float dx = a.x - b.x;
        const float dy = a.y - b.y;
        return std::sqrt(dx * dx + dy * dy);
    }

    struct CanvasSettings
    {
        int width{32};
        int height{32};
        int cellSize{18};
    };

    struct PixelPaint
    {
        int x{};
        int y{};
        ColorRGBA color{};
    };

    struct RectPaint
    {
        Rectangle rect{};
        ColorRGBA color{};
    };

    struct CirclePaint
    {
        Vector2 center{};
        float radius{};
        ColorRGBA color{};
    };

    struct StrokePaint
    {
        Vector2 from{};
        Vector2 to{};
        int thickness{1};
        ColorRGBA color{};
    };

    struct CanvasDocument
    {
        CanvasSettings settings{};
        std::vector<PixelPaint> pixels;
        std::vector<RectPaint> rectangles;
        std::vector<CirclePaint> circles;
        std::vector<StrokePaint> strokes;

        void Clear()
        {
            pixels.clear();
            rectangles.clear();
            circles.clear();
            strokes.clear();
        }
    };

    enum class ToolType
    {
        Pixel,
        Rectangle,
        Circle,
        Stroke
    };

    class CanvasExporter
    {
    public:
        static std::string ExportCpp(const CanvasDocument &doc, const std::string &functionName)
        {
            std::ostringstream out;
            out << "#include \"raylib.h\"\n\n";
            out << "void " << functionName << "()\n";
            out << "{\n";
            out << "    // Generated by the canvas tool.\n";
            out << "    // NOTE: This function is intentionally data-driven and fast enough for UI/runtime reuse.\n\n";

            for (const auto &px : doc.pixels)
            {
                out << "    DrawRectangle(" << px.x << ", " << px.y << ", 1, 1, " << ColorToRaylibCode(px.color) << ");\n";
            }

            for (const auto &rect : doc.rectangles)
            {
                out << "    DrawRectangleRec(Rectangle{" << rect.rect.x << "f, " << rect.rect.y << "f, "
                    << rect.rect.width << "f, " << rect.rect.height << "f}, " << ColorToRaylibCode(rect.color) << ");\n";
            }

            for (const auto &circle : doc.circles)
            {
                out << "    DrawCircleV(Vector2{" << circle.center.x << "f, " << circle.center.y << "f}, "
                    << circle.radius << "f, " << ColorToRaylibCode(circle.color) << ");\n";
            }

            for (const auto &stroke : doc.strokes)
            {
                out << "    DrawLineEx(Vector2{" << stroke.from.x << "f, " << stroke.from.y << "f}, Vector2{" << stroke.to.x << "f, "
                    << stroke.to.y << "f}, " << stroke.thickness << "f, " << ColorToRaylibCode(stroke.color) << ");\n";
            }

            out << "}\n";
            return out.str();
        }

        static bool SaveCpp(const fs::path &path, const CanvasDocument &doc, const std::string &functionName)
        {
            std::ofstream file(path, std::ios::binary);
            if (!file.is_open())
            {
                return false;
            }
            file << ExportCpp(doc, functionName);
            return true;
        }

        static bool SavePngPlaceholder(const fs::path &path, const CanvasDocument &)
        {
            std::ofstream file(path, std::ios::binary);
            if (!file.is_open())
            {
                return false;
            }
            file << "PNG export is reserved for future implementation.";
            return true;
        }
    };

    class CanvasApp
    {
    public:
        CanvasApp()
        {
            document_.settings = {48, 32, 18};
            palette_ = {
                BLACK, WHITE, RED, GREEN, BLUE, YELLOW, ORANGE, PURPLE, PINK, SKYBLUE, DARKGRAY, BROWN
            };
            activeColor_ = RED;
        }

        void Run()
        {
            InitWindow(1600, 980, "Canvas Export Tool");
            SetTargetFPS(60);
            SetExitKey(KEY_NULL);

            while (!WindowShouldClose())
            {
                Update();
                BeginDrawing();
                ClearBackground(Color{24, 24, 28, 255});
                Draw();
                EndDrawing();
            }

            CloseWindow();
        }

    private:
        CanvasDocument document_{};
        ToolType tool_{ToolType::Pixel};
        Color activeColor_{RED};
        std::vector<Color> palette_;
        int brushSize_{1};
        bool isDrawing_{false};
        Vector2 strokeStart_{};
        std::string status_ = "Ready";

        Rectangle CanvasBounds() const
        {
            const float left = 320.0f;
            const float top = 24.0f;
            const float width = static_cast<float>(document_.settings.width * document_.settings.cellSize);
            const float height = static_cast<float>(document_.settings.height * document_.settings.cellSize);
            return Rectangle{left, top, width, height};
        }

        bool InCanvas(Vector2 p) const
        {
            return CheckCollisionPointRec(p, CanvasBounds());
        }

        Vector2 CanvasToGrid(Vector2 p) const
        {
            const Rectangle bounds = CanvasBounds();
            const float localX = p.x - bounds.x;
            const float localY = p.y - bounds.y;
            return Vector2{std::floor(localX / document_.settings.cellSize), std::floor(localY / document_.settings.cellSize)};
        }

        Vector2 GridToCanvas(Vector2 grid) const
        {
            const Rectangle bounds = CanvasBounds();
            return Vector2{bounds.x + grid.x * document_.settings.cellSize, bounds.y + grid.y * document_.settings.cellSize};
        }

        void SetStatus(std::string text)
        {
            status_ = std::move(text);
        }

        void PaintPixelAtGrid(int gx, int gy)
        {
            if (gx < 0 || gy < 0 || gx >= document_.settings.width || gy >= document_.settings.height)
            {
                return;
            }
            document_.pixels.push_back(PixelPaint{gx, gy, ToRGBA(activeColor_)});
        }

        void PaintCurrentTool(Vector2 mouse)
        {
            if (!InCanvas(mouse))
            {
                return;
            }

            if (tool_ == ToolType::Pixel)
            {
                const Vector2 grid = CanvasToGrid(mouse);
                for (int oy = 0; oy < brushSize_; ++oy)
                {
                    for (int ox = 0; ox < brushSize_; ++ox)
                    {
                        PaintPixelAtGrid(static_cast<int>(grid.x) + ox, static_cast<int>(grid.y) + oy);
                    }
                }
            }
        }

        void CommitShape(Vector2 begin, Vector2 end)
        {
            const Rectangle bounds = CanvasBounds();
            const float bx = std::clamp(begin.x, bounds.x, bounds.x + bounds.width);
            const float by = std::clamp(begin.y, bounds.y, bounds.y + bounds.height);
            const float ex = std::clamp(end.x, bounds.x, bounds.x + bounds.width);
            const float ey = std::clamp(end.y, bounds.y, bounds.y + bounds.height);

            if (tool_ == ToolType::Rectangle)
            {
                const float x = std::min(bx, ex);
                const float y = std::min(by, ey);
                const float w = std::abs(ex - bx);
                const float h = std::abs(ey - by);
                document_.rectangles.push_back(RectPaint{Rectangle{x, y, w, h}, ToRGBA(activeColor_)});
            }
            else if (tool_ == ToolType::Circle)
            {
                const float radius = std::max(1.0f, Distance(Vector2{bx, by}, Vector2{ex, ey}));
                document_.circles.push_back(CirclePaint{Vector2{bx, by}, radius, ToRGBA(activeColor_)});
            }
            else if (tool_ == ToolType::Stroke)
            {
                document_.strokes.push_back(StrokePaint{Vector2{bx, by}, Vector2{ex, ey}, std::max(1, brushSize_), ToRGBA(activeColor_)});
            }
        }

        void HandleExport()
        {
            const fs::path outDir = fs::current_path() / "utils" / "exports";
            std::error_code ec;
            fs::create_directories(outDir, ec);

            const std::string functionName = "DrawGeneratedCanvas";
            const fs::path cppPath = outDir / "generated_canvas.cpp";
            const fs::path pngPath = outDir / "future_png_export.stub";

            const bool cppOk = CanvasExporter::SaveCpp(cppPath, document_, functionName);
            const bool pngOk = CanvasExporter::SavePngPlaceholder(pngPath, document_);

            if (cppOk)
            {
                SetClipboardText(CanvasExporter::ExportCpp(document_, functionName).c_str());
            }

            if (cppOk && pngOk)
            {
                SetStatus(TextFormat("Exported: %s", cppPath.string().c_str()));
            }
            else
            {
                SetStatus("Export failed");
            }
        }

        void Update()
        {
            const Vector2 mouse = GetMousePosition();

            if (IsMouseButtonPressed(MOUSE_LEFT_BUTTON))
            {
                if (InCanvas(mouse))
                {
                    isDrawing_ = true;
                    strokeStart_ = mouse;
                    PaintCurrentTool(mouse);
                }
                else
                {
                    HandleSidebarClick(mouse);
                }
            }

            if (isDrawing_ && IsMouseButtonDown(MOUSE_LEFT_BUTTON))
            {
                if (tool_ == ToolType::Pixel)
                {
                    PaintCurrentTool(mouse);
                }
            }

            if (isDrawing_ && IsMouseButtonReleased(MOUSE_LEFT_BUTTON))
            {
                if (tool_ != ToolType::Pixel)
                {
                    CommitShape(strokeStart_, mouse);
                }
                isDrawing_ = false;
            }

            if (IsKeyPressed(KEY_C))
            {
                document_.Clear();
                SetStatus("Canvas cleared");
            }

            if (IsKeyPressed(KEY_E))
            {
                HandleExport();
            }

            if (IsKeyPressed(KEY_KP_ADD) || IsKeyPressed(KEY_EQUAL))
            {
                brushSize_ = std::min(16, brushSize_ + 1);
            }
            if (IsKeyPressed(KEY_KP_SUBTRACT) || IsKeyPressed(KEY_MINUS))
            {
                brushSize_ = std::max(1, brushSize_ - 1);
            }
        }

        void HandleSidebarClick(Vector2 mouse)
        {
            const Rectangle toolRects[] = {
                Rectangle{24, 120, 260, 36},
                Rectangle{24, 166, 260, 36},
                Rectangle{24, 212, 260, 36},
                Rectangle{24, 258, 260, 36},
            };

            for (int i = 0; i < 4; ++i)
            {
                if (CheckCollisionPointRec(mouse, toolRects[i]))
                {
                    tool_ = static_cast<ToolType>(i);
                    SetStatus("Tool changed");
                    return;
                }
            }

            const Rectangle exportButton{24, 792, 260, 44};
            const Rectangle clearButton{24, 844, 260, 44};
            if (CheckCollisionPointRec(mouse, exportButton))
            {
                HandleExport();
                return;
            }
            if (CheckCollisionPointRec(mouse, clearButton))
            {
                document_.Clear();
                SetStatus("Canvas cleared");
                return;
            }

            for (size_t i = 0; i < palette_.size(); ++i)
            {
                const int row = static_cast<int>(i / 6);
                const int col = static_cast<int>(i % 6);
                const Rectangle cell{24.0f + col * 44.0f, 326.0f + row * 44.0f, 36.0f, 36.0f};
                if (CheckCollisionPointRec(mouse, cell))
                {
                    activeColor_ = palette_[i];
                    SetStatus("Color selected");
                    return;
                }
            }
        }

        void DrawButton(const Rectangle &rect, const char *text, bool active = false) const
        {
            DrawRectangleRec(rect, active ? Color{66, 90, 120, 255} : Color{44, 48, 58, 255});
            DrawRectangleLinesEx(rect, 1.0f, Color{90, 96, 110, 255});
            const int fontSize = 20;
            const int textWidth = MeasureText(text, fontSize);
            DrawText(text, static_cast<int>(rect.x + (rect.width - textWidth) / 2), static_cast<int>(rect.y + 8), fontSize, RAYWHITE);
        }

        void DrawCanvas() const
        {
            const Rectangle bounds = CanvasBounds();
            DrawRectangleRec(bounds, Color{240, 240, 242, 255});
            DrawRectangleLinesEx(bounds, 2.0f, Color{120, 120, 130, 255});

            for (int y = 0; y < document_.settings.height; ++y)
            {
                for (int x = 0; x < document_.settings.width; ++x)
                {
                    const Rectangle cell{bounds.x + x * document_.settings.cellSize, bounds.y + y * document_.settings.cellSize,
                                         static_cast<float>(document_.settings.cellSize), static_cast<float>(document_.settings.cellSize)};
                    DrawRectangleLinesEx(cell, 1.0f, Color{220, 220, 224, 255});
                }
            }

            for (const auto &pixel : document_.pixels)
            {
                const Rectangle cell{bounds.x + pixel.x * document_.settings.cellSize, bounds.y + pixel.y * document_.settings.cellSize,
                                     static_cast<float>(document_.settings.cellSize), static_cast<float>(document_.settings.cellSize)};
                DrawRectangleRec(cell, ToColor(pixel.color));
            }

            for (const auto &rect : document_.rectangles)
            {
                DrawRectangleRec(rect.rect, ToColor(rect.color));
            }

            for (const auto &circle : document_.circles)
            {
                DrawCircleV(circle.center, circle.radius, ToColor(circle.color));
            }

            for (const auto &stroke : document_.strokes)
            {
                DrawLineEx(stroke.from, stroke.to, static_cast<float>(stroke.thickness), ToColor(stroke.color));
            }

            if (isDrawing_ && tool_ != ToolType::Pixel)
            {
                const Vector2 mouse = GetMousePosition();
                if (tool_ == ToolType::Rectangle)
                {
                    const float x = std::min(strokeStart_.x, mouse.x);
                    const float y = std::min(strokeStart_.y, mouse.y);
                    const float w = std::abs(mouse.x - strokeStart_.x);
                    const float h = std::abs(mouse.y - strokeStart_.y);
                    DrawRectangleLinesEx(Rectangle{x, y, w, h}, 2.0f, activeColor_);
                }
                else if (tool_ == ToolType::Circle)
                {
                    DrawCircleLines(static_cast<int>(strokeStart_.x), static_cast<int>(strokeStart_.y), Distance(strokeStart_, mouse), activeColor_);
                }
                else if (tool_ == ToolType::Stroke)
                {
                    DrawLineEx(strokeStart_, mouse, static_cast<float>(brushSize_), activeColor_);
                }
            }
        }

        void Draw() const
        {
            DrawText("Canvas Export Tool", 24, 24, 28, RAYWHITE);
            DrawText("LMB: draw | E: export | C: clear | +/-: brush size", 24, 60, 18, Color{180, 185, 200, 255});

            DrawButton(Rectangle{24, 120, 260, 36}, "Pixel Brush", tool_ == ToolType::Pixel);
            DrawButton(Rectangle{24, 166, 260, 36}, "Rectangle", tool_ == ToolType::Rectangle);
            DrawButton(Rectangle{24, 212, 260, 36}, "Circle", tool_ == ToolType::Circle);
            DrawButton(Rectangle{24, 258, 260, 36}, "Line", tool_ == ToolType::Stroke);

            DrawText("Palette", 24, 302, 20, RAYWHITE);
            for (size_t i = 0; i < palette_.size(); ++i)
            {
                const int row = static_cast<int>(i / 6);
                const int col = static_cast<int>(i % 6);
                const Rectangle cell{24.0f + col * 44.0f, 326.0f + row * 44.0f, 36.0f, 36.0f};
                DrawRectangleRec(cell, palette_[i]);
                DrawRectangleLinesEx(cell, 2.0f, Color{60, 60, 70, 255});
                if (ColorIsEqual(palette_[i], activeColor_))
                {
                    DrawRectangleLinesEx(Rectangle{cell.x - 2, cell.y - 2, cell.width + 4, cell.height + 4}, 2.0f, WHITE);
                }
            }

            DrawText(TextFormat("Brush: %d", brushSize_), 24, 530, 20, RAYWHITE);
            DrawText(TextFormat("Canvas: %dx%d", document_.settings.width, document_.settings.height), 24, 560, 20, RAYWHITE);

            DrawText("PNG hook reserved", 24, 604, 18, Color{160, 170, 180, 255});
            DrawRectangleRounded(Rectangle{24, 792, 260, 44}, 0.2f, 6, Color{50, 120, 80, 255});
            DrawText("Export", 122, 804, 20, WHITE);
            DrawRectangleRounded(Rectangle{24, 844, 260, 44}, 0.2f, 6, Color{120, 70, 70, 255});
            DrawText("Clear", 128, 856, 20, WHITE);

            DrawCanvas();
            DrawText(status_.c_str(), 24, 920, 18, Color{220, 220, 230, 255});
        }
    };
}

int main()
{
    CanvasApp app;
    app.Run();
    return 0;
}
