#include "raylib.h"

void DrawGeneratedCanvas()
{
    // Generated by the canvas tool.

    DrawCircleV(Vector2{7.5f, 15.25f}, 1f, Color{230, 41, 55, 255});
    DrawCircleV(Vector2{12.875f, 18.75f}, 5.48293f, Color{230, 41, 55, 255});
}
